version: "3.9"

services:
  app:
    build:
      context: .
    image: zmteamimage
    volumes:
      - ./:/ZMTeam
    stdin_open: true # docker run -i
    command:
      sh -c "python db/run_migrations.py && /bin/bash"

